<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>LuxLoop | Official</title>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet" />
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      font-family: 'Poppins', sans-serif;
    }

    body {
      background: linear-gradient(135deg, #111, #1c1c1c);
      color: white;
      min-height: 100vh;
    }

    nav {
      background: #1f1f1f;
      display: flex;
      justify-content: space-around;
      padding: 1rem 0;
      border-bottom: 2px solid #ff007f;
    }

    nav a {
      color: white;
      text-decoration: none;
      font-weight: 600;
      padding: 0.5rem 1rem;
      transition: background-color 0.3s ease, transform 0.3s ease;
    }

    nav a:hover {
      background-color: #ff007f;
      border-radius: 8px;
      transform: scale(1.05);
    }

    section {
      display: none;
      padding: 3rem 1rem;
      text-align: center;
      transition: opacity 0.5s ease;
    }

    section.active {
      display: block;
    }

    #home.active {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      height: calc(100vh - 80px);
    }

    h1 {
      font-size: 3rem;
      margin-bottom: 0.5rem;
      color: #fff;
      text-shadow: 0 0 10px #ff007f, 0 0 20px #ff007f, 0 0 30px #ff007f;
      animation: glow 2s ease-in-out infinite alternate;
    }

    @keyframes glow {
      from {
        text-shadow: 0 0 10px #ff007f, 0 0 20px #ff007f, 0 0 30px #ff007f;
      }
      to {
        text-shadow: 0 0 20px #ff00aa, 0 0 30px #ff00aa, 0 0 40px #ff00aa;
      }
    }

    p {
      color: #bbb;
      margin-bottom: 2rem;
    }

    .buttons {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 20px;
    }

    .btn-row {
      display: flex;
      gap: 20px;
      flex-wrap: wrap;
      justify-content: center;
    }

    .btn {
      background: #ff007f;
      padding: 15px 25px;
      border-radius: 12px;
      color: white;
      text-decoration: none;
      font-weight: 600;
      box-shadow: 0 4px 15px rgba(255, 0, 127, 0.3);
      transition: all 0.3s ease-in-out;
      position: relative;
      overflow: hidden;
    }

    .btn::after {
      content: "";
      position: absolute;
      width: 120%;
      height: 100%;
      top: 0;
      left: -10%;
      background: rgba(255, 255, 255, 0.1);
      transform: skewX(-20deg);
      transition: left 0.3s ease;
    }

    .btn:hover {
      transform: scale(1.07);
      box-shadow: 0 6px 25px rgba(255, 0, 127, 0.5);
    }

    .btn:hover::after {
      left: 110%;
    }

    .btn.shop {
      width: 240px;
      text-align: center;
    }

    .gallery {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 30px;
      padding: 2rem;
      width: 100%;
    }

    .gallery img {
      width: 100%;
      border-radius: 15px;
      box-shadow: 0 6px 20px rgba(255, 0, 127, 0.15);
      transition: transform 0.3s ease;
    }

    .gallery img:hover {
      transform: scale(1.03);
    }

    footer {
      text-align: center;
      color: #666;
      font-size: 0.9rem;
      padding: 2rem 0;
    }
  </style>
</head>
<body>
  <nav>
    <a href="#" onclick="showTab('home')">Home</a>
    <a href="#" onclick="showTab('products')">Products</a>
  </nav>

  <!-- Home Section -->
  <section id="home" class="active">
    <h1>LuxLoop</h1>
    <p>Follow & shop with us:</p>
    <div class="buttons">
      <div class="btn-row">
        <a class="btn" href="https://www.instagram.com/shop_luxloop/" target="_blank">Instagram</a>
        <a class="btn" href="https://www.facebook.com/profile.php?id=61577972342463" target="_blank">Facebook</a>
      </div>
      <a class="btn shop" href="https://www.facebook.com/marketplace/profile/61577972342463/" target="_blank">FB SHOP</a>
    </div>
  </section>

  <!-- Products Section -->
  <section id="products">
    <h1>Our Products</h1>
    <p>Browse some of our featured items below.</p>
    <div class="gallery">
      <img src="LuxLoop.png" alt="Classic Blue Perfume" />
    </div>
  </section>

  <footer>© 2025 LuxLoop. All rights reserved.</footer>

  <script>
    function showTab(tabId) {
      document.querySelectorAll('section').forEach(sec => {
        sec.classList.remove('active');
      });
      document.getElementById(tabId).classList.add('active');
    }
  </script>
</body>
</html>
